apiVersion: v1
kind: Service
metadata:
  name: time-app-service
spec:
  type: NodePort
  selector:
    app: time-app
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 32000
